### ISSUE TITLE
Observables not being added to state

### ISSUE THREAD

**Issue by bayesianbrad** [Tobias-Kohn/PyFOPPL#11]
Thanks for fixes #9 and #10. When the state is generated in `gen_prior_samples()` it uses `gen_all_keys()`. However, `gen_all_keys()` does not contain any of the observables `y...`. 
It should hopefully be a super simple fix, thanks again!

**Comment by Tobias-Kohn** [comment]
I have added the observables to `gen_all_keys()`. It is indeed a very small matter to change that. 
But please make sure that you and Yuan are asking for the same thing ^_^. If I recall correctly, the `gen_all_keys()` was specifically supposed to leave out the observables.
